// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"HIME_EquipSlotsCore","status":true,"description":"v1.5 - Provides you with tools to set up custom equip slots\r\nfor each actor individually.","parameters":{}},
{"name":"HIME_WeaponDamage","status":true,"description":"v1.3 - Define weapon damage formulas and separate them from\r\nskill damage formulas.","parameters":{"Bare-Hands Weapon ID":"1\r"}},
{"name":"HIME_EnemyEquips","status":true,"description":"v1.3 - Allows you to give enemies equips. Provides\r\nfunctionality for managing enemy equips.","parameters":{}}
];
